05-12 03:14:55 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "TEST_TABLE" already exists; SQL statement:
CREATE TABLE test_table (id int primary key, value varchar(255)) [42101-170]
05-12 03:14:55 jdbc[2]: exception
org.h2.jdbc.JdbcBatchUpdateException: Table "TEST_TABLE" already exists; SQL statement:
CREATE TABLE test_table (id int primary key, value varchar(255)) [42101-170]
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:634)
	at clojure.java.jdbc$execute_batch.invoke(jdbc.clj:400)
	at clojure.java.jdbc$db_do_commands$fn__2423.invoke(jdbc.clj:671)
	at clojure.java.jdbc$db_transaction_STAR_.doInvoke(jdbc.clj:580)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.java.jdbc$db_do_commands.doInvoke(jdbc.clj:670)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:634)
	at clojure.java.jdbc$db_do_commands.doInvoke(jdbc.clj:677)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:636)
	at clojure.java.jdbc$db_do_commands.doInvoke(jdbc.clj:664)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at base_project.model.db$init_BANG_.invoke(db.clj:10)
	at base_project.model.db$eval2714.invoke(form-init3876284972749567141.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.eval(Compiler.java:6745)
	at clojure.core$eval.invoke(core.clj:3081)
	at clojure.main$repl$read_eval_print__7099$fn__7102.invoke(main.clj:240)
	at clojure.main$repl$read_eval_print__7099.invoke(main.clj:240)
	at clojure.main$repl$fn__7108.invoke(main.clj:258)
	at clojure.main$repl.doInvoke(main.clj:258)
	at clojure.lang.RestFn.invoke(RestFn.java:1523)
	at clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__2516.invoke(interruptible_eval.clj:48)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:630)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1868)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eval.clj:46)
	at clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__2558$fn__2561.invoke(interruptible_eval.clj:178)
	at clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__2551.invoke(interruptible_eval.clj:147)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
org.h2.jdbc.JdbcSQLException: Table "TEST_TABLE" already exists; SQL statement:
CREATE TABLE test_table (id int primary key, value varchar(255)) [42101-170]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:108)
	at org.h2.command.CommandContainer.update(CommandContainer.java:75)
	at org.h2.command.Command.executeUpdate(Command.java:230)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:125)
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:619)
	at clojure.java.jdbc$execute_batch.invoke(jdbc.clj:400)
	at clojure.java.jdbc$db_do_commands$fn__2423.invoke(jdbc.clj:671)
	at clojure.java.jdbc$db_transaction_STAR_.doInvoke(jdbc.clj:580)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.java.jdbc$db_do_commands.doInvoke(jdbc.clj:670)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:634)
	at clojure.java.jdbc$db_do_commands.doInvoke(jdbc.clj:677)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:636)
	at clojure.java.jdbc$db_do_commands.doInvoke(jdbc.clj:664)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at base_project.model.db$init_BANG_.invoke(db.clj:10)
	at base_project.model.db$eval2714.invoke(form-init3876284972749567141.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.eval(Compiler.java:6745)
	at clojure.core$eval.invoke(core.clj:3081)
	at clojure.main$repl$read_eval_print__7099$fn__7102.invoke(main.clj:240)
	at clojure.main$repl$read_eval_print__7099.invoke(main.clj:240)
	at clojure.main$repl$fn__7108.invoke(main.clj:258)
	at clojure.main$repl.doInvoke(main.clj:258)
	at clojure.lang.RestFn.invoke(RestFn.java:1523)
	at clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__2516.invoke(interruptible_eval.clj:48)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:630)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1868)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eval.clj:46)
	at clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__2558$fn__2561.invoke(interruptible_eval.clj:178)
	at clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__2551.invoke(interruptible_eval.clj:147)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
05-12 03:41:20 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "TEST_TABLE" not found; SQL statement:
select * from test_table [42102-170]
05-12 03:44:55 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "TEST_TABLE" not found; SQL statement:
select * from test_table [42102-170]
